name: CI/CD for ktsp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Initialize Gradle
      run: gradle init
      working-directory: ./SpringBoot

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.5.1
        arguments: build
      working-directory: ./SpringBoot

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push ktsp image
      run: |
        docker build -t leesw0924/ktsp ./SpringBoot/
        docker push leesw0924/ktsp
        docker build -t leesw0924/ktsp_db ./Database/
        docker push leesw0924/ktsp_db

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH to EC2 and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.KTSP_EC2_HOST }}
        username: ${{ secrets.KTSP_EC2_USERNAME }}
        key: ${{ secrets.KTSP_EC2_PRIVATE_KEY }}
        script: |
          echo "${{ secrets.KTSP_COMPOSE_YML }}" > /home/ubuntu/ktsp/compose.yml
          cd /home/ubuntu/ktsp
          docker compose up -d --pull always
          docker image prune -f